### ISSUE TITLE
Updating giscus id settings

### ISSUE THREAD

**Issue by r12f** [zkp-co-learning/zkp-co-learning.github.io#16]
Hi @Demian101 , 

Do you mind to help update the giscus settings in the theme? 

It is currently set to using the "r12f/sonic-book" as the destination, so all the comments of this book will be created under the sonic-book repo discussions as below:

- https://github.com/r12f/sonic-book/discussions/23
- https://github.com/r12f/sonic-book/discussions/22

This is the file and key code for the settings: <https://github.com/zkp-co-learning/zkp-co-learning.github.io/blob/main/theme/index.hbs>

And the new settings can be crafted by using this app here: https://giscus.app/.

```js
        <script src="https://giscus.app/client.js"
                data-repo="r12f/sonic-book"
                data-repo-id="R_kgDOJhBB1g"
                data-category="Comments"
                data-category-id="DIC_kwDOJhBB1s4CXctO"
                data-mapping="og:title"
                data-strict="0"
                data-reactions-enabled="1"
                data-emit-metadata="0"
                data-input-position="top"
                data-theme="dark_dimmed"
                data-lang="en"
                data-loading="lazy"
                crossorigin="anonymous"
                async>
        </script>
```

**Comment by Demian101** [comment]
thank you for pointing this out，I shall fix it 🤣

**Comment by r12f** [comment]
Thanks a lot! 🥰

**Comment by Demian101** [comment]
The problem has been resolved and no further action is required
