### ISSUE TITLE
halo2-chap1 public_inputs should be "out" 

### ISSUE THREAD

**Issue by Nickqiaoo** [zkp-co-learning/zkp-co-learning.github.io#42]
![image](https://github.com/zkp-co-learning/zkp-co-learning.github.io/assets/16211196/559e0507-8035-4224-b16a-99a317a40284)
The public_inputs is "out"

**Comment by Nickqiaoo** [comment]
#41 fix here

**Comment by Demian101** [comment]
GREAT WORK !
